repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  exclude:
  hooks:
  - id: check-merge-conflict
  - id: check-ast
  - id: check-byte-order-marker
#  - id: trailing-whitespace
#    args: ['--markdown-linebreak-ext=*']
#  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=no]
